// Country code to country name mapping for common football nations
export const countryCodeToName = {
  // European countries
  ENG: "England",
  ESP: "Spain",
  FRA: "France",
  GER: "Germany",
  ITA: "Italy",
  POR: "Portugal",
  NED: "Netherlands",
  BEL: "Belgium",
  SCO: "Scotland",
  WAL: "Wales",
  IRL: "Ireland",
  NIR: "Northern Ireland",
  AUT: "Austria",
  SUI: "Switzerland",
  DEN: "Denmark",
  SWE: "Sweden",
  NOR: "Norway",
  POL: "Poland",
  CZE: "Czech Republic",
  SVK: "Slovakia",
  HUN: "Hungary",
  CRO: "Croatia",
  SRB: "Serbia",
  BIH: "Bosnia and Herzegovina",
  SVN: "Slovenia",
  MKD: "North Macedonia",
  ALB: "Albania",
  MNE: "Montenegro",
  GRE: "Greece",
  TUR: "Turkey",
  RUS: "Russia",
  UKR: "Ukraine",
  BLR: "Belarus",
  LTU: "Lithuania",
  LVA: "Latvia",
  EST: "Estonia",
  FIN: "Finland",
  ISL: "Iceland",
  ROU: "Romania",
  BUL: "Bulgaria",

  // South American countries
  BRA: "Brazil",
  ARG: "Argentina",
  URU: "Uruguay",
  COL: "Colombia",
  CHI: "Chile",
  PAR: "Paraguay",
  PER: "Peru",
  ECU: "Ecuador",
  BOL: "Bolivia",
  VEN: "Venezuela",

  // North/Central American countries
  USA: "United States",
  MEX: "Mexico",
  CAN: "Canada",
  CRC: "Costa Rica",
  HON: "Honduras",
  GUA: "Guatemala",
  ESA: "El Salvador",
  PAN: "Panama",
  NCA: "Nicaragua",
  JAM: "Jamaica",

  // African countries
  NGA: "Nigeria",
  GHA: "Ghana",
  SEN: "Senegal",
  CIV: "Ivory Coast",
  CMR: "Cameroon",
  MAR: "Morocco",
  TUN: "Tunisia",
  ALG: "Algeria",
  EGY: "Egypt",
  RSA: "South Africa",
  KEN: "Kenya",
  ZIM: "Zimbabwe",
  MLI: "Mali",
  BFA: "Burkina Faso",
  GUI: "Guinea",
  GAB: "Gabon",
  CGO: "Congo",
  ANG: "Angola",

  // Asian countries
  JPN: "Japan",
  KOR: "South Korea",
  CHN: "China",
  AUS: "Australia",
  IRN: "Iran",
  KSA: "Saudi Arabia",
  UAE: "United Arab Emirates",
  QAT: "Qatar",
  JOR: "Jordan",
  IRQ: "Iraq",
  SYR: "Syria",
  LBN: "Lebanon",
  ISR: "Israel",
  UZB: "Uzbekistan",
  KGZ: "Kyrgyzstan",
  KAZ: "Kazakhstan",
  TJK: "Tajikistan",
  AFG: "Afghanistan",
  IND: "India",
  THA: "Thailand",
  VIE: "Vietnam",
  MAS: "Malaysia",
  SIN: "Singapore",
  IDN: "Indonesia",
  PHI: "Philippines",

  // Other regions
  NZL: "New Zealand",
  FIJ: "Fiji",
  NCL: "New Caledonia",
  TAH: "Tahiti",
};

// Function to get full country name from code
export const getCountryName = (countryCode) => {
  if (!countryCode) return "Unknown";

  const upperCode = countryCode.toString().toUpperCase();
  return countryCodeToName[upperCode] || countryCode; // Return original code if not found
};
